name: Update Status Task

on:
  schedule:
    # 毎日 UTC 15:00 = 日本時間 0:00 に実行
    - cron: '0 15 * * *'
  workflow_dispatch: # 手動実行も可能にする
  push:
    branches:
      - feature/change_status # 現在の作業ブランチ
      - main 

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.10
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run consultation schedule update status task
        env:
          RAILS_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle exec rake consultation_schedule:update_status

      #失敗時の通知
      - name: Notify on failure
        if: failure()
        run: echo "Task failed. Please check the logs."